Repository kinoplan/scalajs-react-material-ui, pull requests merged in 2021-12, with the labels that each got.

#86 Update sbt to 1.5.6
  project/build.properties
Labels: dependencies

#88 Update sbt to 1.5.7
  project/build.properties
Labels: dependencies

#89 Update sbt to 1.5.8
  project/build.properties
Labels: dependencies

#81 Update sbt-scalafix to 0.9.33
  project/plugins.sbt
Labels: dependencies

#79 Update organize-imports to 0.6.0
  scalafix.sbt
Labels: dependencies

#67 Update scalajs-dom to 1.2.0
  project/Dependencies.scala
Labels: dependencies

#48 Update scala-library to 2.13.6
  build.sbt
  demo/src/main/scala/io/kinoplan/demo/utils/Helpers.scala
Labels: dependencies

#78 Update scala-library to 2.13.7
  build.sbt
Labels: dependencies

#87 Update sbt-scalajs, scalajs-compiler, ... to 1.8.0
  project/plugins.sbt
Labels: dependencies

#92 Add release drafter
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: build

#94 Refactoring *.sbt & project/*.scala files
  build.sbt
  commands.sbt
  project/BridgeGeneratorPlugin.scala
  project/Dependencies.scala
  project/Generator.scala
  project/Modules.scala
  project/MuiColorsGeneratorPlugin.scala
  project/MuiIconsGeneratorPlugin.scala
  project/ProjectSettings.scala
  project/Settings.scala
  project/plugins.sbt
Labels: refactor

#96 Dependencies/update
  .github/workflows/build.yml
  .mergify.yml
  core/src/main/scala/io/kinoplan/scalajs/react/material/ui/core/MuiChip.scala
  core/src/main/scala/io/kinoplan/scalajs/react/material/ui/core/MuiFormControlLabel.scala
  core/src/main/scala/io/kinoplan/scalajs/react/material/ui/core/MuiNativeSelect.scala
  core/src/main/scala/io/kinoplan/scalajs/react/material/ui/core/MuiSelect.scala
  core/src/main/scala/io/kinoplan/scalajs/react/material/ui/core/MuiStepper.scala
  core/src/main/scala/io/kinoplan/scalajs/react/material/ui/core/package.scala
  demo/dev.webpack.config.js
  demo/lib/scalajs-react-material-ui-icons_sjs1_2.13-0.1.0+1-5e41edb4+20201105-1130-SNAPSHOT.jar
  demo/src/main/scala/io/kinoplan/demo/components/demos/AppBar/MenuAppBar.scala
  demo/src/main/scala/io/kinoplan/demo/components/demos/AppBar/PrimarySearchAppBar.scala
  demo/src/main/scala/io/kinoplan/demo/components/demos/Menus/FadeMenu.scala
  demo/src/main/scala/io/kinoplan/demo/components/demos/Menus/LongMenu.scala
  demo/src/main/scala/io/kinoplan/demo/components/demos/Menus/SimpleListMenu.scala
  demo/src/main/scala/io/kinoplan/demo/components/demos/Menus/SimpleMenu.scala
  demo/src/main/scala/io/kinoplan/demo/components/demos/Selects/MultipleSelect.scala
  demo/src/main/scala/io/kinoplan/demo/components/demos/Selects/SimpleSelect.scala
  demo/src/main/scala/io/kinoplan/demo/components/demos/Tables/wrappers/EnhancedTableToolbar.scala
  demo/src/main/scala/io/kinoplan/demo/models/Tables/Row.scala
  demo/src/main/scala/io/kinoplan/demo/utils/CSSUtils.scala
  demo/src/main/scala/io/kinoplan/demo/utils/props/MuiInputProps.scala
  lab/src/main/scala/io/kinoplan/scalajs/react/material/ui/lab/MuiSlider.scala
  lab/src/main/scala/io/kinoplan/scalajs/react/material/ui/lab/MuiSpeedDial.scala
  lab/src/main/scala/io/kinoplan/scalajs/react/material/ui/lab/package.scala
  project/Dependencies.scala
  project/DependenciesNPM.scala
  project/Modules.scala
  project/ProjectSettings.scala
  project/plugins.sbt
  utils/bridge/src/main/scala/io/kinoplan/scalajs/react/bridge/package.scala
Labels: dependencies

#97 Update scalajs-dom to 2.1.0
  project/Dependencies.scala
Labels: dependencies

#95 Update sbt to 1.6.1
  project/build.properties
Labels: dependencies

#82 Update cats-core to 2.7.0
  project/Dependencies.scala
Labels: dependencies
